services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machakos_site
    hostname: machakos_postgres
    restart: always
    environment:
      POSTGRES_USER: elvis87
      POSTGRES_PASSWORD: elvis87
      POSTGRES_DB: soishop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - soi_network
  mysql:
    image: mysql:8.0
    container_name: nairobi_site
    hostname: nairobi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elvis87
      MYSQL_DATABASE: soishop
      MYSQL_USER: elvis87
      MYSQL_PASSWORD: elvis87
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - soi_network
  mariadb:
    image: mariadb:10.7
    container_name: makueni_site
    hostname: makueni_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elvis87
      MYSQL_DATABASE: soishop
      MYSQL_USER: elvis87
      MYSQL_PASSWORD: elvis87
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - soi_network

networks:
  soi_network:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mariadb_data: